# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd224d48850e820c4e08485e628462c01f1f70a4bba9377141319a3bbb8c2bea88b38ec72246152611eca2e24b3b27e75e45a55d737b6023640d742dd94027d

test:
  secret_key_base: d309b2ade02be835aa3d0429206d47f46f3648d1cbb1f573b0917a3e639fd274e49a92e1b9ef8b3e4cafd0bd059912e620750c23569a9dcdc155805f7b725587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
